<?php

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$sCompteGithub = "fabrice1618";
$sRepository = "github_commit";
$path = "";

$client = new \Github\Client();
try {
//    $commits = $this->client->api('repo')->commits()->all($this->username, $repo, ['path' => $path]);
    $aCommit = $client->api('repo')->commits()->all($sCompteGithub, $sRepository, ['path' => $path]);
    print_r($aCommit);

  } catch (\RuntimeException $e) {
    echo "Erreur acces API Github";
  }
